### ISSUE TITLE
Reexport fails after `workspace()`

### ISSUE THREAD

**Issue by NHDaly** [simonster/Reexport.jl#14]
Originally https://github.com/JuliaPlots/StatPlots.jl/issues/146

[julia v0.6]

Hi, it seems that the `@reexport` fails inside `StatPlots.jl` after calling `workspace()`:

```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin14.5.0

julia> using StatPlots; workspace(); using StatPlots; workspace(); using StatPlots
[...]
MethodError: all(::Reexport.##2#6, ::Array{Any,1}) is ambiguous. Candidates:
  all(f, A::AbstractArray{#s18,N} where N where #s18>:LastMain.Missings.Missing) in LastMain.Missings at /Users/daly/.julia/v0.6/Missings/src/Missings.jl:190
  all(f, A::AbstractArray{#s18,N} where N where #s18>:LastMain.LastMain.Missings.Missing) in LastMain.LastMain.Missings at /Users/daly/.julia/v0.6/Missings/src/Missings.jl:190
Possible fix, define
  all(::Any, ::AbstractArray{#s18,N} where N where #s18>:Union{LastMain.LastMain.Missings.Missing, LastMain.Missings.Missing})(Array
Stacktrace:{T, N
} where N where  [1] T, Main.include_from_node1Base.LinAlg.(Diagonal{T}:: where T, ArrayString{T, N)} where N where  at T) in module Optim at /Users/daly/.julia/v0.6/Optim/src/multivariate/precon.jl:47./loading.jl:576 overwritten in module Optim at /Users/daly/.julia/v0.6/Optim/src/multivariate/precon.jl:47.
```

**Comment by NHDaly** [comment]
Does this seem to you like it could be a problem in `Reexport`? I wasn't able to reproduce it with tiny example modules, but i'm not very familiar with what Reexport is doing.

Ah, sorry, the stacktrace got cut off in the previous message. Here's a better example:

```julia
julia> using StatPlots
ERROR: LoadError: MethodError: all(::Reexport.##2#6, ::Array{Any,1}) is ambiguous. Candidates:
  all(f, A::AbstractArray{#s18,N} where N where #s18>:Missings.Missing) in Missings at /Users/daly/.julia/v0.6/Missings/src/Missings.jl:190
  all(f, A::AbstractArray{#s18,N} where N where #s18>:LastMain.Missings.Missing) in LastMain.Missings at /Users/daly/.julia/v0.6/Missings/src/Missings.jl:190
Possible fix, define
  all(::Any, ::AbstractArray{#s18,N} where N where #s18>:Union{LastMain.Missings.Missing, Missings.Missing})
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] eval(::Module, ::Any) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [3] _require(::Symbol) at ./loading.jl:490
 [4] require(::Symbol) at ./loading.jl:405
while loading /Users/daly/.julia/v0.6/StatPlots/src/StatPlots.jl, in expression starting on line 5

```

**Comment by NHDaly** [comment]
And [StatPlots/src/StatPlots.jl line 5](https://github.com/JuliaPlots/StatPlots.jl/blob/2aa99e0ed3be629f2ababd14c39017a63ac319a4/src/StatPlots.jl#L5) is:
```
@reexport using Plots
```

**Comment by ararslan** [comment]
Does this happen without using `workspace()`? That function is notorious for interacting poorly with packages, which is partly why it was deprecated in 0.7.

**Comment by NHDaly** [comment]
I believe not. I think that `workspace` is exactly what's wrong here.  I intended this Issue to be basically: "I'm sad, Reexport doesn't seem to play nicely with `workspace`."

I'll re-name the issue accordingly.

**Comment by NHDaly** [comment]
Is there any idea about _why_ it's not working in this case? And could we/I fix it? Or is it one of those things that's just not worth doing since, as you say, support for `workspace()` is being dropped?

**Comment by ararslan** [comment]
I don't know what there is to be done to address it here and I don't think there will be any changes to `workspace` made and backported to Julia 0.6. I suspect such issues aren't limited to Reexport, that just happens to be a currently visible offender.

I think people use Revise in place of `workspace`, though I've not tried it myself. In these situations I just restart Julia.

**Comment by NHDaly** [comment]
I see. Thanks. We've just removed `workspace` from the code then. Thanks Alex!

**Comment by ararslan** [comment]
I'm going to go ahead and close this, since there's no action to be taken here.

**Comment by NHDaly** [comment]
👍 Sorry i didn't do that myself

**Comment by miguelmorin** [comment]
The `Revise` solution by @ararslan works well. This is not specific to `Reexport` or `StatsPlots`. I added an answer [here](https://stackoverflow.com/questions/25028873/how-do-i-reload-a-module-in-an-active-julia-session-after-an-edit/50816280#50816280).
