### ISSUE TITLE
@reexport using ModuleA: functionB, functionC

### ISSUE THREAD

**Issue by gaika** [simonster/Reexport.jl#20]
How hard is it to support `@reexport using ModuleA: functionB, functionC` syntax?

**Comment by ararslan** [comment]
Probably pretty straightforward. For `using M: a, b`, we just extract the `a` and `b` from
```julia
Expr(:using, Expr(:(:), :M, Expr(:., :a), Expr(:., :b)))
```
and produce
```julia
Expr(:export, :a, :b)
```

**Comment by ararslan** [comment]
Fixed by #21.

**Comment by johnnychen94** [comment]
Could we bump a version for this?

**Comment by ararslan** [comment]
See #23.
