### ISSUE TITLE
broken @reexport using ModuleA: functionB, functionC 

### ISSUE THREAD

**Issue by mchristianl** [simonster/Reexport.jl#22]
Hi there,

using

```julia
@reexport using Base: sin, cos
```

currently gives me a

```
ERROR: syntax: malformed expression
Stacktrace:
 [1] top-level scope at none:0
```

maybe something in the syntax-tree representation was changed recently?

```julia
@macroexpand @reexport using Base: sin, cos
```

gives

```julia
:($(Expr(:toplevel, :(using Base: sin, cos), :(eval(Expr(:export, names($(Expr(:., :cos)))...))))))
```

regards,
Christian

**Comment by ararslan** [comment]
Is this with the master branch of the package? That functionality hasn't made it into a release yet.

**Comment by mchristianl** [comment]
Of course! Sorry.

using the master branch with
```
(v1.2) pkg> develop Reexport
```

works fine.
