### ISSUE TITLE
Re-export deprecated bindings

### ISSUE THREAD

**Issue by mzgubic** [simonster/Reexport.jl#28]
This came up recently when we [renamed a few types](https://github.com/JuliaDiff/ChainRulesCore.jl/pull/353) in `ChainRules`, which uses `@reexport` macro to reexport the `ChainRulesCore` differential types, e.g. `Zero` was renamed to `ZeroTangent`.

This broke [`ReversePropagation` tests](https://github.com/JuliaDiff/ChainRules.jl/pull/413/checks?check_run_id=2618918423) (as part of the `ChainRules` integration tests suite) because `ReversePropagation` only depends on `ChainRules` directly (rather than `ChainRulesCore`), and did not understand the deprecated `Zero`.

**Comment by ararslan** [comment]
So is the proposal here to have `@reexport using X` avoid exporting a binding if it's deprecated by `X`? Note that would turn deprecations, which are typically non-breaking, into hard errors downstream.

**Comment by oxinabox** [comment]
I think the opposite, I think the problem is right now it doesn't reexport the old names?

**Comment by johnnychen94** [comment]
The problem is that `my_old_sum` now is not exported.

```julia
julia> module LargePackage
           using Reexport

           module SmallPackage
               export my_new_sum

               my_new_sum(A::Tuple) = reduce(+, A)

               Base.@deprecate_binding my_old_sum my_new_sum
           end

           @reexport using .SmallPackage
       end # module
Main.LargePackage

julia> using .LargePackage

julia> my_old_sum((1, 2))
ERROR: UndefVarError: my_old_sum not defined
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```

Curiously, if we use `@deprecate` here it just works.

**Comment by ararslan** [comment]
> Curiously, if we use `@deprecate` here it just works.

That's because the expansion of `@deprecate` includes an `export` by default. One of the arguments to the macro toggles that.

**Comment by ararslan** [comment]
Okay, I see the problem now: `names` doesn't see deprecated bindings by default (that's documented). I think that instead of iterating over `names(M)` for `M` a `Module`, we'd need to do something like
```julia
for binding in names(M; all=true, imported=true)
    if Base.isexported(M, binding)
        # reexport binding
    end
end
```
